# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-23 10:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0002_activity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='detail',
        ),
        migrations.AddField(
            model_name='activity',
            name='connected',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='activity',
            name='time_left',
            field=models.IntegerField(default=0),
        ),
    ]
