# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-23 10:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0004_auto_20170423_1044'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='connected',
        ),
    ]
