# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-23 10:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0010_auto_20170423_1048'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='detail',
            field=models.CharField(default='', max_length=100),
        ),
    ]
