# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-30 07:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0011_activity_detail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activity',
            old_name='time_left',
            new_name='spend_time',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='connected',
        ),
    ]
