# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-30 08:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0012_auto_20170430_0740'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activity',
            old_name='spend_time',
            new_name='time_left',
        ),
        migrations.AddField(
            model_name='activity',
            name='connected',
            field=models.BooleanField(default=False),
        ),
    ]
