# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-11 09:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0013_auto_20170430_0846'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='mail',
            field=models.EmailField(default='', max_length=254),
        ),
    ]
